
dist: trusty

language: go

go:
    - 1.8.3

install:
  - go get github.com/gohugoio/hugo

script:
  - git clone https://travis-ci:$GITHUB_API_KEY@github.com/sharatvisweswara/sharatvisweswara.github.io.git public
  - hugo

after_success:
  - cd public && git add -A && git commit -m "rebuilding site at $(date)" && git push
