
dist: trusty

language: go

go:
    - 1.8.3

install:
  - go get -v github.com/gohugoio/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_API_KEY
  repo: sharatvisweswara.github.io
  target_branch: master
  on:
    branc: master
